version: '2'
services:

  # The Application
  app:
    image: big-data-project
    container_name: big-data-project
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "APP_ENV=${APP_ENV}"
      - "CONTAINER_ROLE=app"
