version: '2'
services:

  # The Application
  app:
    image: big-data-project
    container_name: big-data-project
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=${DB_PORT}"
      - "DB_HOST=database"
      - "APP_ENV=${APP_ENV}"
      - "CONTAINER_ROLE=app"

#  scheduler:
#    container_name: get-that-gpu-scheduler
#    depends_on:
#      - app
#    build:
#      context: ./
#      dockerfile: scheduler.dockerfile
#    volumes:
#      - .:/var/www
#    environment:
#      - "DB_PORT=${DB_PORT}"
#      - "DB_HOST=database"
#      - "APP_ENV=${APP_ENV}"
#      - "CONTAINER_ROLE=scheduler"

  # The Web Server
#  web:
#    container_name: get-that-gpu-web
#    build:
#      context: ./
#      args:
#        - USER1=${BASICAUTH_USER1}
#        - PASS1=${BASICAUTH_PASS1}
#        - USER2=${BASICAUTH_USER2}
#        - PASS2=${BASICAUTH_PASS2}
#        - USER3=${BASICAUTH_USER3}
#        - PASS3=${BASICAUTH_PASS3}
#      dockerfile: web.dockerfile
#    working_dir: /var/www
#    volumes_from:
#      - app
#    ports:
#      - "${APP_PORT}:80"
#    environment:
#      - "CONTAINER_ROLE=web"

  # The Database
#  database:
#    container_name: get-that-gpu-db
#    image: mariadb:10.3.6
#    volumes:
#      - dbdata:/var/lib/mysql
#    environment:
#      - "MYSQL_DATABASE=${DB_DATABASE}"
#      - "MYSQL_USER=${DB_USERNAME}"
#      - "MYSQL_PASSWORD=${DB_PASSWORD}"
#      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
#      - "TZ=${TIMEZONE}"
#    ports:
#        - "33061:${DB_PORT}"

#volumes:
#  dbdata:
